export const ADD_EVENT = 'ADD_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
export const SET_EVENTS = 'SET_EVENTS';
export const SEARCH_EVENTS = 'SEARCH_EVENTS';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';

export const ADD_PERSON = 'ADD_PERSON';
export const REMOVE_PERSON = 'REMOVE_PERSON';

export const ADD_VENUE_CHANGE = 'ADD_VENUE_CHANGE';
export const ADD_VENUE_SUBMIT = 'ADD_VENUE_SUBMIT';

export const SEARCH_POZNAN_VENUES = 'SEARCH_POZNAN_VENUES';
